export const sentimentdata = [
  { input: { bom: 1, fantástico: 1, ótimo: 1 }, output: { positivo: 1 } },
  { input: { excelente: 1, ótimo: 1 }, output: { positivo: 1 } },
  { input: { incrível: 1, maravilhoso: 1 }, output: { positivo: 1 } },
  { input: { feliz: 1, alegria: 1 }, output: { positivo: 1 } },
  { input: { amor: 1, gostei: 1 }, output: { positivo: 1 } },
  { input: { ruim: 1, horrível: 1 }, output: { negativo: 1 } },
  { input: { terrível: 1, pavoroso: 1 }, output: { negativo: 1 } },
  { input: { pobre: 1, decepcionante: 1 }, output: { negativo: 1 } },
  { input: { triste: 1, infeliz: 1 }, output: { negativo: 1 } },
  { input: { odeio: 1, desgostei: 1 }, output: { negativo: 1 } },
  { input: { prazer: 1, favorito: 1 }, output: { positivo: 1 } },
  { input: { legal: 1, melhor: 1 }, output: { positivo: 1 } },
  { input: { incrível: 1, alegre: 1 }, output: { positivo: 1 } },
  { input: { sortudo: 1, doce: 1 }, output: { positivo: 1 } },
  { input: { sucesso: 1, vitória: 1 }, output: { positivo: 1 } },
  { input: { fracasso: 1, derrota: 1 }, output: { negativo: 1 } },
  { input: { pavor: 1, medo: 1 }, output: { negativo: 1 } },
  { input: { feio: 1, horrível: 1 }, output: { negativo: 1 } },
  { input: { nojento: 1, cruel: 1 }, output: { negativo: 1 } },
  { input: { miserável: 1, azarado: 1 }, output: { negativo: 1 } },
  { input: { ruim: 1, horrível: 1 }, output: { negativo: 1 } },
  { input: { nojento: 1, repulsivo: 1 }, output: { negativo: 1 } },
  { input: { irado: 1, incrível: 1 }, output: { positivo: 1 } },
  { input: { pior: 1, ruim: 1 }, output: { negativo: 1 } },
  { input: { melhor: 1, bom: 1 }, output: { positivo: 1 } },
  { input: { positivo: 1, agradável: 1 }, output: { positivo: 1 } },
  { input: { negativo: 1, entediante: 1 }, output: { negativo: 1 } },
  { input: { frágil: 1 }, output: { negativo: 1 } },
  { input: { fraco: 1 }, output: { negativo: 1 } },
  { input: { puto: 1 }, output: { negativo: 1 } },
  { input: { força: 1 }, output: { positivo: 1 } },
  { input: { burro: 1 }, output: { negativo: 1 } },
  { input: { idiota: 1 }, output: { negativo: 1 } },
  { input: { safado: 1 }, output: { negativo: 1 } },
  { input: { feio: 1 }, output: { negativo: 1 } },
  { input: { nada: 1 }, output: { negativo: 1 } },
  { input: { tudo: 1 }, output: { negativo: 1 } },
  { input: { status: 1 }, output: { positivo: 1 } },
  { input: { dinheiro: 1 }, output: { neutro: 1 } },
  { input: { aceito: 1 }, output: { positivo: 1 } },
  { input: { recuso: 1 }, output: { negativo: 1 } },
  { input: { não: 1 }, output: { negativo: 1 } },
  { input: { sim: 1 }, output: { positivo: 1 } },
  { input: { pode: 1 }, output: { positivo: 1 } },
  { input: { quero: 1 }, output: { positivo: 1 } },
  { input: { ain: 1 }, output: { negativo: 1 } },
  { input: { dor: 1 }, output: { negativo: 1 } },
  { input: { conhecer: 1 }, output: { positivo: 1 } },
  { input: { aprender: 1 }, output: { positivo: 1 } },
  { input: { beijar: 1 }, output: { positivo: 1 } },
  { input: { abraçar: 1 }, output: { positivo: 1 } },
  { input: { economizar: 1 }, output: { positivo: 1 } },
  { input: { arrumar: 1 }, output: { positivo: 1 } },
  { input: { limpar: 1 }, output: { positivo: 1 } },
  { input: { amar: 1 }, output: { positivo: 1 } },
  { input: { nenhum: 1 }, output: { negativo: 1 } },
  { input: { burnout: 1 }, output: { negativo: 1 } },
  { input: { rir: 1 }, output: { positivo: 1 } },
  { input: { sorrir: 1 }, output: { positivo: 1 } },
  { input: { chorar: 1 }, output: { negativo: 1 } },
  { input: { ajudar: 1 }, output: { positivo: 1 } },
  { input: { atrapalhar: 1 }, output: { negativo: 1 } },
  { input: { ocupado: 1 }, output: { negativo: 1 } },
  { input: { sentido: 1 }, output: { positivo: 1 } },
  { input: { sentir: 1 }, output: { positivo: 1 } },
  { input: { preguiça: 1 }, output: { negativo: 1 } },
  { input: { valor: 1 }, output: { positivo: 1 } },
  { input: { tesão: 1 }, output: { positivo: 1 } },
  { input: { exibir: 1 }, output: { positivo: 1 } },
  { input: { diversão: 1 }, output: { positivo: 1 } },
  { input: { morrer: 1 }, output: { negativo: 1 } },
  { input: { viver: 1 }, output: { positivo: 1 } },
  { input: { tomar: 1 }, output: { negativo: 1 } },
  { input: { roubar: 1 }, output: { negativo: 1 } },
  { input: { cu: 1 }, output: { negativo: 1 } },
  { input: { buceta: 1 }, output: { negativo: 1 } },
  { input: { caralho: 1 }, output: { negativo: 1 } },
  { input: { gostei: 1 }, output: { positivo: 1 } },
];
