version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always

  bot:
    build: ./bot
    environment:
      - DISCORD_TOKEN=coloque_seu_token_aqui
    depends_on:
      - backend
    restart: always
