export const sentimentdata = [
  { input: { bão: 1 }, output: { positivo: 1 } },
  { input: { lover: 1 }, output: { positivo: 1 } },
  { input: { love: 1 }, output: { positivo: 1 } },
  { input: { bem: 1 }, output: { positivo: 1 } },
  { input: { bom: 1, fantástico: 1, ótimo: 1 }, output: { positivo: 1 } },
  { input: { excelente: 1, ótimo: 1 }, output: { positivo: 1 } },
  { input: { incrível: 1, maravilhoso: 1 }, output: { positivo: 1 } },
  { input: { feliz: 1, alegria: 1 }, output: { positivo: 1 } },
  { input: { amor: 1, gostar: 1 }, output: { positivo: 1 } },
  { input: { ruim: 1, horrível: 1 }, output: { negativo: 1 } },
  { input: { terrível: 1, pavoroso: 1 }, output: { negativo: 1 } },
  { input: { pobre: 1, decepcionante: 1 }, output: { negativo: 1 } },
  { input: { triste: 1, infeliz: 1 }, output: { negativo: 1 } },
  { input: { odiar: 1, desgostar: 1 }, output: { negativo: 1 } },
  { input: { prazer: 1, favorito: 1 }, output: { positivo: 1 } },
  { input: { legal: 1, melhor: 1 }, output: { positivo: 1 } },
  { input: { incrível: 1, alegre: 1 }, output: { positivo: 1 } },
  { input: { sortudo: 1, doce: 1 }, output: { positivo: 1 } },
  { input: { sucesso: 1, vitória: 1 }, output: { positivo: 1 } },
  { input: { fracasso: 1, derrota: 1 }, output: { negativo: 1 } },
  { input: { pavor: 1, medo: 1 }, output: { negativo: 1 } },
  { input: { feio: 1, horrível: 1 }, output: { negativo: 1 } },
  { input: { nojento: 1, cruel: 1 }, output: { negativo: 1 } },
  { input: { miserável: 1, azarar: 1 }, output: { negativo: 1 } },
  { input: { ruim: 1, horrível: 1 }, output: { negativo: 1 } },
  { input: { nojento: 1, repulsivo: 1 }, output: { negativo: 1 } },
  { input: { irado: 1, incrível: 1 }, output: { positivo: 1 } },
  { input: { pior: 1, ruim: 1 }, output: { negativo: 1 } },
  { input: { melhor: 1, bom: 1 }, output: { positivo: 1 } },
  { input: { positivo: 1, agradável: 1 }, output: { positivo: 1 } },
  { input: { negativo: 1, entediante: 1 }, output: { negativo: 1 } },
  { input: { frágil: 1 }, output: { negativo: 1 } },
  { input: { fraco: 1 }, output: { negativo: 1 } },
  { input: { puto: 1 }, output: { negativo: 1 } },
  { input: { força: 1 }, output: { positivo: 1 } },
  { input: { burro: 1 }, output: { negativo: 1 } },
  { input: { idiota: 1 }, output: { negativo: 1 } },
  { input: { safado: 1 }, output: { negativo: 1 } },
  { input: { feio: 1 }, output: { negativo: 1 } },
  { input: { nada: 1 }, output: { neutro: 1 } },
  { input: { tudo: 1 }, output: { neutro: 1 } },
  { input: { status: 1 }, output: { positivo: 1 } },
  { input: { dinheiro: 1 }, output: { neutro: 1 } },
  { input: { aceito: 1 }, output: { positivo: 1 } },
  { input: { recuso: 1 }, output: { negativo: 1 } },
  { input: { não: 1 }, output: { negativo: 1 } },
  { input: { sim: 1 }, output: { positivo: 1 } },
  { input: { pode: 1 }, output: { positivo: 1 } },
  { input: { quero: 1 }, output: { positivo: 1 } },
  { input: { ain: 1 }, output: { negativo: 1 } },
  { input: { dor: 1 }, output: { negativo: 1 } },
  { input: { conhecer: 1 }, output: { positivo: 1 } },
  { input: { aprender: 1 }, output: { positivo: 1 } },
  { input: { beijar: 1 }, output: { positivo: 1 } },
  { input: { abraçar: 1 }, output: { positivo: 1 } },
  { input: { economizar: 1 }, output: { positivo: 1 } },
  { input: { arrumar: 1 }, output: { positivo: 1 } },
  { input: { limpar: 1 }, output: { positivo: 1 } },
  { input: { amar: 1 }, output: { positivo: 1 } },
  { input: { nenhum: 1 }, output: { negativo: 1 } },
  { input: { burnout: 1 }, output: { negativo: 1 } },
  { input: { rir: 1 }, output: { positivo: 1 } },
  { input: { sorrir: 1 }, output: { positivo: 1 } },
  { input: { chorar: 1 }, output: { negativo: 1 } },
  { input: { ajudar: 1 }, output: { positivo: 1 } },
  { input: { atrapalhar: 1 }, output: { negativo: 1 } },
  { input: { ocupado: 1 }, output: { negativo: 1 } },
  { input: { sentido: 1 }, output: { positivo: 1 } },
  { input: { sentir: 1 }, output: { positivo: 1 } },
  { input: { preguiça: 1 }, output: { negativo: 1 } },
  { input: { valor: 1 }, output: { positivo: 1 } },
  { input: { tesão: 1 }, output: { positivo: 1 } },
  { input: { exibir: 1 }, output: { positivo: 1 } },
  { input: { diversão: 1 }, output: { positivo: 1 } },
  { input: { morrer: 1 }, output: { negativo: 1 } },
  { input: { viver: 1 }, output: { positivo: 1 } },
  { input: { tomar: 1 }, output: { negativo: 1 } },
  { input: { roubar: 1 }, output: { negativo: 1 } },
  { input: { cu: 1 }, output: { negativo: 1 } },
  { input: { buceta: 1 }, output: { negativo: 1 } },
  { input: { caralho: 1 }, output: { negativo: 1 } },
  { input: { gostei: 1 }, output: { positivo: 1 } },
  { input: { top: 1 }, output: { positivo: 1 } },
  { input: { daora: 1 }, output: { positivo: 1 } },
  { input: { dahora: 1 }, output: { positivo: 1 } },
  { input: { massa: 1 }, output: { positivo: 1 } },
  { input: { amei: 1 }, output: { positivo: 1 } },
  { input: { apaixonado: 1 }, output: { positivo: 1 } },
  { input: { lindx: 1 }, output: { positivo: 1 } },
  { input: { lindão: 1 }, output: { positivo: 1 } },
  { input: { delícia: 1 }, output: { positivo: 1 } },
  { input: { arrasou: 1 }, output: { positivo: 1 } },
  { input: { show: 1 }, output: { positivo: 1 } },
  { input: { hype: 1 }, output: { positivo: 1 } },
  { input: { foda: 1 }, output: { positivo: 1 } },
  { input: { confiante: 1 }, output: { positivo: 1 } },
  { input: { tranquilão: 1 }, output: { positivo: 1 } },
  { input: { sabedoria: 1 }, output: { positivo: 1 } },
  { input: { paz: 1 }, output: { positivo: 1 } },
  { input: { curti: 1 }, output: { positivo: 1 } },
  { input: { tesudo: 1 }, output: { positivo: 1 } },
  { input: { gostoso: 1 }, output: { positivo: 1 } },
  { input: { gracinha: 1 }, output: { positivo: 1 } },
  { input: { brilho: 1 }, output: { positivo: 1 } },
  { input: { raiva: 1 }, output: { negativo: 1 } },
  { input: { ódio: 1 }, output: { negativo: 1 } },
  { input: { cansado: 1 }, output: { negativo: 1 } },
  { input: { estressado: 1 }, output: { negativo: 1 } },
  { input: { desgraça: 1 }, output: { negativo: 1 } },
  { input: { fodido: 1 }, output: { negativo: 1 } },
  { input: { fracassado: 1 }, output: { negativo: 1 } },
  { input: { chato: 1 }, output: { negativo: 1 } },
  { input: { tédio: 1 }, output: { negativo: 1 } },
  { input: { bosta: 1 }, output: { negativo: 1 } },
  { input: { merda: 1 }, output: { negativo: 1 } },
  { input: { lixo: 1 }, output: { negativo: 1 } },
  { input: { babaca: 1 }, output: { negativo: 1 } },
  { input: { otário: 1 }, output: { negativo: 1 } },
  { input: { babaca: 1 }, output: { negativo: 1 } },
  { input: { corno: 1 }, output: { negativo: 1 } },
  { input: { inveja: 1 }, output: { negativo: 1 } },
  { input: { ansiedade: 1 }, output: { negativo: 1 } },
  { input: { depressão: 1 }, output: { negativo: 1 } },
  { input: { fudido: 1 }, output: { negativo: 1 } },
  { input: { fudida: 1 }, output: { negativo: 1 } },
  { input: { ferrado: 1 }, output: { negativo: 1 } },
  { input: { desmotivado: 1 }, output: { negativo: 1 } },
  { input: { tanto: 1 }, output: { neutro: 1 } },
  { input: { coisa: 1 }, output: { neutro: 1 } },
  { input: { alguém: 1 }, output: { neutro: 1 } },
  { input: { ninguém: 1 }, output: { neutro: 1 } },
  { input: { talvez: 1 }, output: { neutro: 1 } },
  { input: { tipo: 1 }, output: { neutro: 1 } },
  { input: { enfim: 1 }, output: { neutro: 1 } },
  { input: { sei: 1 }, output: { neutro: 1 } },
  { input: { vamo: 1 }, output: { neutro: 1 } },
  { input: { bora: 1 }, output: { neutro: 1 } },
  { input: { partiu: 1 }, output: { neutro: 1 } },
  { input: { tô: 1 }, output: { neutro: 1 } },
  { input: { tá: 1 }, output: { neutro: 1 } },
  { input: { num: 1 }, output: { neutro: 1 } },
  { input: { pq: 1 }, output: { neutro: 1 } },
  { input: { vlw: 1 }, output: { positivo: 1 } },
  { input: { flw: 1 }, output: { neutro: 1 } },
  { input: { brabo: 1 }, output: { negativo: 1 } },
  { input: { vibe: 1 }, output: { positivo: 1 } },
  { input: { rolê: 1 }, output: { positivo: 1 } },
  { input: { topzera: 1 }, output: { positivo: 1 } },
  { input: { insano: 1 }, output: { positivo: 1 } },
  { input: { desesperado: 1 }, output: { negativo: 1 } },
  { input: { lol: 1 }, output: { positivo: 1 } },
  { input: { hit: 1 }, output: { neutro: 1 } },
  { input: { clipe: 1 }, output: { neutro: 1 } },
  { input: { chocado: 1 }, output: { neutro: 1 } },
  { input: { epic: 1 }, output: { positivo: 1 } },
  { input: { zoeiro: 1 }, output: { neutro: 1 } },
  { input: { meme: 1 }, output: { neutro: 1 } },
  { input: { flex: 1 }, output: { positivo: 1 } },
  { input: { fodase: 1 }, output: { negativo: 1 } },
  { input: { troll: 1 }, output: { negativo: 1 } },
  { input: { fake: 1 }, output: { negativo: 1 } },
  { input: { incrível: 1 }, output: { positivo: 1 } },
  { input: { parado: 1 }, output: { neutro: 1 } },
  { input: { mental: 1 }, output: { neutro: 1 } },
  { input: { memeiro: 1 }, output: { neutro: 1 } },
  { input: { beleza: 1 }, output: { positivo: 1 } },
  { input: { cancelado: 1 }, output: { negativo: 1 } },
  { input: { merda: 1 }, output: { negativo: 1 } },
  { input: { bombando: 1 }, output: { positivo: 1 } },
  { input: { gostosa: 1 }, output: { positivo: 1 } },
  { input: { carai: 1 }, output: { negativo: 1 } },
  { input: { brisa: 1 }, output: { neutro: 1 } },
  { input: { bolado: 1 }, output: { negativo: 1 } },
  { input: { desafiador: 1 }, output: { positivo: 1 } },
  { input: { realidade: 1 }, output: { neutro: 1 } },
  { input: { empolgado: 1 }, output: { positivo: 1 } },
  { input: { ótimo: 1 }, output: { positivo: 1 } },
  { input: { desolado: 1 }, output: { negativo: 1 } },
  { input: { rolando: 1 }, output: { neutro: 1 } },
  { input: { energia: 1 }, output: { positivo: 1 } },
  { input: { carinhoso: 1 }, output: { positivo: 1 } },
  { input: { bacana: 1 }, output: { positivo: 1 } },
  { input: { revoltado: 1 }, output: { negativo: 1 } },
  { input: { chato: 1 }, output: { negativo: 1 } },
  { input: { confusão: 1 }, output: { negativo: 1 } },
  { input: { motivado: 1 }, output: { positivo: 1 } },
  { input: { caótico: 1 }, output: { negativo: 1 } },
  { input: { empurrar: 1 }, output: { neutro: 1 } },
  { input: { zica: 1 }, output: { positivo: 1 } },
  { input: { fracassado: 1 }, output: { negativo: 1 } },
  { input: { farsa: 1 }, output: { negativo: 1 } },
  { input: { desencorajado: 1 }, output: { negativo: 1 } },
  { input: { viciado: 1 }, output: { negativo: 1 } },
  { input: { absurdamente: 1 }, output: { neutro: 1 } },
  { input: { demorando: 1 }, output: { negativo: 1 } },
  { input: { desafiante: 1 }, output: { neutro: 1 } },
  { input: { ansioso: 1 }, output: { neutro: 1 } },
  { input: { mandando: 1 }, output: { negativo: 1 } },
  { input: { arrebentando: 1 }, output: { positivo: 1 } },
  { input: { insatisfeito: 1 }, output: { negativo: 1 } },
  { input: { hype: 1 }, output: { positivo: 1 } },
  { input: { marrento: 1 }, output: { negativo: 1 } },
  { input: { arrasou: 1 }, output: { positivo: 1 } },
];
